version: '3.8'

services:
  # Initialize volume permissions
  init-volumes:
    image: busybox
    container_name: init-volumes
    command: >
      sh -c "
      mkdir -p /data/workflows &&
      mkdir -p /logs/grpc/dossier &&
      chown -R ${UID:-1000}:${GID:-1000} /data &&
      chown -R ${UID:-1000}:${GID:-1000} /logs &&
      echo 'Volume permissions initialized for UID=${UID:-1000} GID=${GID:-1000}'
      "
    volumes:
      - ./docker/volumes/workflow-data:/data
      - ./docker/volumes/logs:/logs
    user: "0:0"  # Run as root to set permissions
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}

  workflow-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: rust-workflow-server
    depends_on:
      init-volumes:
        condition: service_completed_successfully
    network_mode: host  # Use host network to access local services
    volumes:
      - ./config:/app/config:ro  # Configuration files
      - ./templates:/app/templates:ro  # ODT template files
      - ./docker/volumes/workflow-data:/data  # Persistent workflow data (local bind mount)
      - ./docker/volumes/logs:/logs  # Logs directory for debugging
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "workflow-server", "--help"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
